//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.11 at 09:24:12 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sernet.de/sync/data", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.sernet.sync.data;
